language: php

matrix:
  include:
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: xenial
    - php: 8.0
      dist: bionic
    - php: 8.1.0
      dist: bionic
    - php: nightly
      dist: bionic
  allow_failures:
    - php: nightly

before_install: true

install:
  - eval `ssh-agent -s`
  - git clone -b 2.0 --single-branch https://github.com/phpseclib/phpseclib.git temp
  - mv temp/tests tests
  - rm tests/Functional/Net/SCPSSH2UserStoryTest.php
  - rm tests/Unit/Net/SSH1Test.php
  - rm tests/Unit/Net/SSH2UnitTest.php
  - rm tests/Unit/Math/BigInteger/InternalTest.php
  - sed -i 's/%s\/..\/phpseclib\/%s/%s\/..\/src\/%s/g' tests/PhpseclibTestCase.php
  - sed -i 's/public function testSetPrivate()/private function skiptestSetPrivate()/g' tests/Unit/Crypt/RSA/LoadKeyTest.php
  - sed -i 's/public function testOAEPWithLabel()/private function skiptestOAEPWithLabel()/g' tests/Unit/Crypt/RSA/ModeTest.php
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.5' ]; then vendor/bin/phing -f build/build.xml sniff; fi"
  - mv temp/travis travis
  - travis/setup-secure-shell.sh
  - travis/setup-composer.sh

script:
  - travis/run-phpunit.sh